// Mock data for Taste platform

export const MOCK_USER = {
  id: "u1",
  username: "alex_cinema",
  display_name: "Alex",
  bio: "Slow burn enthusiast. 70s European cinema devotee.",
  avatar_url: "",
  archetype: "Melancholic Formalist",
  archetype_desc: "Haunted by 70s European cinema, soft spot for unreliable narrators",
  stats: {
    total_films: 847,
    total_series: 63,
    total_hours: 2140,
    total_episodes: 1204,
  },
  taste_dna: {
    top_genres: [
      { name: "Drama", pct: 42 },
      { name: "Thriller", pct: 28 },
      { name: "Documentary", pct: 18 },
      { name: "Sci-Fi", pct: 8 },
      { name: "Comedy", pct: 4 },
    ],
    top_directors: ["Andrei Tarkovsky", "Ingmar Bergman", "Wong Kar-wai", "David Lynch", "Agnès Varda"],
    decade_dist: [
      { decade: "1950s", pct: 8 },
      { decade: "1960s", pct: 12 },
      { decade: "1970s", pct: 24 },
      { decade: "1980s", pct: 14 },
      { decade: "1990s", pct: 16 },
      { decade: "2000s", pct: 12 },
      { decade: "2010s", pct: 10 },
      { decade: "2020s", pct: 4 },
    ],
    avg_rating: 3.7,
    critical_divergence: -0.4,
  },
};

export const MOCK_FILMS = [
  {
    id: "f1",
    tmdb_id: 424,
    title: "Schindler's List",
    year: 1993,
    poster_url: "https://image.tmdb.org/t/p/w300/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    tmdb_rating: 8.6,
    user_rating: 5.0,
    genres: ["Drama", "History", "War"],
    runtime: 195,
    director: "Steven Spielberg",
    type: "film",
    status: "watched",
  },
  {
    id: "f2",
    tmdb_id: 637,
    title: "In the Mood for Love",
    year: 2000,
    poster_url: "https://image.tmdb.org/t/p/w300/l1a0WCx4LOsbTJoqnSr2WJCOWEF.jpg",
    tmdb_rating: 8.1,
    user_rating: 5.0,
    genres: ["Drama", "Romance"],
    runtime: 98,
    director: "Wong Kar-wai",
    type: "film",
    status: "watched",
  },
  {
    id: "f3",
    tmdb_id: 289,
    title: "Stalker",
    year: 1979,
    poster_url: "https://image.tmdb.org/t/p/w300/gcpOrBQGNhfwmEFbgb0EMjHlPyX.jpg",
    tmdb_rating: 8.2,
    user_rating: 5.0,
    genres: ["Drama", "Sci-Fi"],
    runtime: 162,
    director: "Andrei Tarkovsky",
    type: "film",
    status: "watched",
  },
  {
    id: "f4",
    tmdb_id: 314,
    title: "Mulholland Drive",
    year: 2001,
    poster_url: "https://image.tmdb.org/t/p/w300/mbBBHO4M3NsYbpTERlyBirNrFqA.jpg",
    tmdb_rating: 7.9,
    user_rating: 4.5,
    genres: ["Drama", "Thriller", "Mystery"],
    runtime: 147,
    director: "David Lynch",
    type: "film",
    status: "watched",
  },
  {
    id: "f5",
    tmdb_id: 539,
    title: "Parasite",
    year: 2019,
    poster_url: "https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    tmdb_rating: 8.5,
    user_rating: 4.5,
    genres: ["Thriller", "Drama", "Comedy"],
    runtime: 132,
    director: "Bong Joon-ho",
    type: "film",
    status: "watched",
  },
  {
    id: "f6",
    tmdb_id: 861,
    title: "Jeanne Dielman",
    year: 1975,
    poster_url: "https://image.tmdb.org/t/p/w300/hSn66SLb3QkR8hcgdIi26ptpXiy.jpg",
    tmdb_rating: 7.8,
    user_rating: 4.5,
    genres: ["Drama"],
    runtime: 201,
    director: "Chantal Akerman",
    type: "film",
    status: "watchlist",
  },
  {
    id: "f7",
    tmdb_id: 129,
    title: "Spirited Away",
    year: 2001,
    poster_url: "https://image.tmdb.org/t/p/w300/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    tmdb_rating: 8.5,
    user_rating: 4.0,
    genres: ["Animation", "Fantasy"],
    runtime: 125,
    director: "Hayao Miyazaki",
    type: "film",
    status: "watched",
  },
  {
    id: "f8",
    tmdb_id: 1124,
    title: "The Godfather",
    year: 1972,
    poster_url: "https://image.tmdb.org/t/p/w300/3bhkrj58Vtu7enYsLeMMovruo8P.jpg",
    tmdb_rating: 8.7,
    user_rating: 4.5,
    genres: ["Drama", "Crime"],
    runtime: 175,
    director: "Francis Ford Coppola",
    type: "film",
    status: "watched",
  },
];

export const MOCK_SERIES = [
  {
    id: "s1",
    title: "The Wire",
    year: 2002,
    poster_url: "https://image.tmdb.org/t/p/w300/4lsJ4ELFOmh2oJADzwCN4Rm3c3N.jpg",
    tmdb_rating: 8.9,
    user_rating: 5.0,
    genres: ["Drama", "Crime"],
    seasons: 5,
    episodes: 60,
    watched_episodes: 60,
    status: "completed",
    type: "series",
    next_episode: null,
  },
  {
    id: "s2",
    title: "Twin Peaks",
    year: 1990,
    poster_url: "https://image.tmdb.org/t/p/w300/kvCHVBd4xSObFPnLs6JrzJhAlqe.jpg",
    tmdb_rating: 8.8,
    user_rating: 4.5,
    genres: ["Drama", "Mystery", "Thriller"],
    seasons: 3,
    episodes: 48,
    watched_episodes: 32,
    status: "watching",
    type: "series",
    next_episode: { season: 2, episode: 14, title: "Double Play" },
  },
  {
    id: "s3",
    title: "Severance",
    year: 2022,
    poster_url: "https://image.tmdb.org/t/p/w300/bxAg0poFKAoRqKJPm4dv7OvNajl.jpg",
    tmdb_rating: 8.7,
    user_rating: null,
    genres: ["Sci-Fi", "Thriller", "Drama"],
    seasons: 2,
    episodes: 19,
    watched_episodes: 0,
    status: "watchlist",
    type: "series",
    next_episode: { season: 1, episode: 1, title: "Good News About Hell" },
  },
  {
    id: "s4",
    title: "Barry",
    year: 2018,
    poster_url: "https://image.tmdb.org/t/p/w300/ndoA4n8MbmGMBRDxSEipcPkNmFO.jpg",
    tmdb_rating: 8.4,
    user_rating: 4.5,
    genres: ["Drama", "Comedy", "Crime"],
    seasons: 4,
    episodes: 32,
    watched_episodes: 18,
    status: "watching",
    type: "series",
    next_episode: { season: 3, episode: 2, title: "The Least Dangerous Man" },
  },
];

export const MOCK_FEED = [
  {
    id: "feed1",
    user: { username: "marina_f", display_name: "Marina F.", avatar_url: "" },
    type: "log",
    title: "Aftersun",
    year: 2022,
    poster_url: "https://image.tmdb.org/t/p/w300/lKoGMkLuEMHBQiPxBFqFQnKGnCr.jpg",
    rating: 5.0,
    note: "I haven't stopped thinking about this film since I finished it. The Super 8 footage at the end broke something in me.",
    timestamp: "2 hours ago",
    media_type: "film",
  },
  {
    id: "feed2",
    user: { username: "kirill_w", display_name: "Kirill W.", avatar_url: "" },
    type: "log",
    title: "Succession S04E03",
    year: 2023,
    poster_url: "https://image.tmdb.org/t/p/w300/e2X7zeHWHLELKQblhB0GNcTkEBo.jpg",
    rating: 4.5,
    note: "Connor's Wedding. TV doesn't get better than this.",
    timestamp: "4 hours ago",
    media_type: "series",
    episode: "S04E03",
  },
  {
    id: "feed3",
    user: { username: "sol_diaz", display_name: "Sol Díaz", avatar_url: "" },
    type: "list",
    list_name: "Films I've watched while sick",
    list_count: 12,
    timestamp: "6 hours ago",
    preview_posters: [
      "https://image.tmdb.org/t/p/w300/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      "https://image.tmdb.org/t/p/w300/3bhkrj58Vtu7enYsLeMMovruo8P.jpg",
      "https://image.tmdb.org/t/p/w300/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      "https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    ],
  },
  {
    id: "feed4",
    user: { username: "anna_k", display_name: "Anna K.", avatar_url: "" },
    type: "log",
    title: "Poor Things",
    year: 2023,
    poster_url: "https://image.tmdb.org/t/p/w300/kCGlIMHnOm8JPXIHTp0QOi7VNYo.jpg",
    rating: 4.0,
    note: null,
    timestamp: "8 hours ago",
    media_type: "film",
  },
  {
    id: "feed5",
    user: { username: "tom_v", display_name: "Tom V.", avatar_url: "" },
    type: "log",
    title: "Oppenheimer",
    year: 2023,
    poster_url: "https://image.tmdb.org/t/p/w300/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    rating: 3.5,
    note: "Technically staggering. Emotionally thin. The Trinity test sequence is one of the great cinema moments of the decade though.",
    timestamp: "Yesterday",
    media_type: "film",
  },
];

export const MOCK_CHAPTERS = [
  {
    id: "c1",
    title: "A long stretch of Kurosawa, November 2023",
    date_start: "Nov 2023",
    date_end: "Dec 2023",
    posters: [
      "https://image.tmdb.org/t/p/w300/3bhkrj58Vtu7enYsLeMMovruo8P.jpg",
      "https://image.tmdb.org/t/p/w300/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      "https://image.tmdb.org/t/p/w300/gcpOrBQGNhfwmEFbgb0EMjHlPyX.jpg",
      "https://image.tmdb.org/t/p/w300/l1a0WCx4LOsbTJoqnSr2WJCOWEF.jpg",
    ],
    count: 14,
  },
  {
    id: "c2",
    title: "The Wire consumed October entirely",
    date_start: "Oct 2023",
    date_end: "Oct 2023",
    posters: [
      "https://image.tmdb.org/t/p/w300/4lsJ4ELFOmh2oJADzwCN4Rm3c3N.jpg",
      "https://image.tmdb.org/t/p/w300/e2X7zeHWHLELKQblhB0GNcTkEBo.jpg",
      "https://image.tmdb.org/t/p/w300/kvCHVBd4xSObFPnLs6JrzJhAlqe.jpg",
      "https://image.tmdb.org/t/p/w300/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    ],
    count: 60,
  },
  {
    id: "c3",
    title: "Late-night documentary phase, July–August 2023",
    date_start: "Jul 2023",
    date_end: "Aug 2023",
    posters: [
      "https://image.tmdb.org/t/p/w300/mbBBHO4M3NsYbpTERlyBirNrFqA.jpg",
      "https://image.tmdb.org/t/p/w300/kCGlIMHnOm8JPXIHTp0QOi7VNYo.jpg",
      "https://image.tmdb.org/t/p/w300/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      "https://image.tmdb.org/t/p/w300/lKoGMkLuEMHBQiPxBFqFQnKGnCr.jpg",
    ],
    count: 18,
  },
];

export const MOCK_INSIGHT_CARDS = [
  {
    id: "i1",
    text: "You've watched 12 films from 1970s Italy this year. That's in the top 3% of all Taste users.",
    type: "rare",
  },
  {
    id: "i2",
    text: "You consistently rate horror films 0.8 stars lower than your average — but you keep watching them. What are you looking for?",
    type: "behavioral",
  },
  {
    id: "i3",
    text: "3 of your top 5 films this year were directed by women. That's up from 1 last year.",
    type: "growth",
  },
  {
    id: "i4",
    text: "You've finished 94% of the shows you've started. The average Taste user finishes 67%. You're a completionist.",
    type: "personality",
  },
];

export const MOCK_TASTE_TWINS = [
  {
    id: "tt1",
    username: "yuki_m",
    display_name: "Yuki M.",
    archetype: "Quiet Observer",
    match_score: 91,
    overlap_count: 73,
    discovery_count: 41,
  },
  {
    id: "tt2",
    username: "felix_r",
    display_name: "Felix R.",
    archetype: "Chaos Romantic",
    match_score: 87,
    overlap_count: 61,
    discovery_count: 38,
  },
  {
    id: "tt3",
    username: "priya_s",
    display_name: "Priya S.",
    archetype: "Suburban Existentialist",
    match_score: 84,
    overlap_count: 54,
    discovery_count: 29,
  },
];

export const MOCK_HEATMAP = {
  title: "Twin Peaks",
  seasons: [
    {
      number: 1,
      episodes: [
        { ep: 1, title: "Pilot", rating: 9.1 },
        { ep: 2, title: "Traces to Nowhere", rating: 8.6 },
        { ep: 3, title: "Zen", rating: 8.4 },
        { ep: 4, title: "Rest in Pain", rating: 8.3 },
        { ep: 5, title: "The One-Armed Man", rating: 8.5 },
        { ep: 6, title: "Cooper's Dreams", rating: 8.7 },
        { ep: 7, title: "Realization Time", rating: 8.6 },
        { ep: 8, title: "The Last Evening", rating: 9.2 },
      ],
    },
    {
      number: 2,
      episodes: [
        { ep: 1, title: "May the Giant Be with You", rating: 8.8 },
        { ep: 2, title: "Coma", rating: 8.5 },
        { ep: 3, title: "The Man Behind Glass", rating: 8.3 },
        { ep: 4, title: "Laura's Secret Diary", rating: 8.4 },
        { ep: 5, title: "The Orchid's Curse", rating: 8.2 },
        { ep: 6, title: "Demons", rating: 8.1 },
        { ep: 7, title: "Lonely Souls", rating: 9.4 },
        { ep: 8, title: "Drive with a Dead Girl", rating: 7.8 },
        { ep: 9, title: "Arbitrary Law", rating: 8.9 },
        { ep: 10, title: "Dispute Between Brothers", rating: 7.5 },
        { ep: 11, title: "Masked Ball", rating: 7.3 },
        { ep: 12, title: "The Black Widow", rating: 7.2 },
        { ep: 13, title: "Checkmate", rating: 7.4 },
        { ep: 14, title: "Double Play", rating: 7.3 },
        { ep: 15, title: "Slaves and Masters", rating: 7.6 },
        { ep: 16, title: "The Condemned Woman", rating: 7.4 },
        { ep: 17, title: "Wounds and Scars", rating: 7.5 },
        { ep: 18, title: "On the Wings of Love", rating: 7.3 },
        { ep: 19, title: "Variations on Relations", rating: 7.4 },
        { ep: 20, title: "The Path to the Black Lodge", rating: 8.2 },
        { ep: 21, title: "Miss Twin Peaks", rating: 8.5 },
        { ep: 22, title: "Beyond Life and Death", rating: 9.5 },
      ],
    },
    {
      number: 3,
      episodes: [
        { ep: 1, title: "The Return Part 1", rating: 8.7 },
        { ep: 2, title: "The Return Part 2", rating: 8.9 },
        { ep: 3, title: "The Return Part 3", rating: 9.1 },
        { ep: 4, title: "The Return Part 4", rating: 8.8 },
        { ep: 5, title: "The Return Part 5", rating: 8.6 },
        { ep: 6, title: "The Return Part 6", rating: 8.7 },
        { ep: 7, title: "The Return Part 7", rating: 8.5 },
        { ep: 8, title: "The Return Part 8", rating: 9.7 },
        { ep: 9, title: "The Return Part 9", rating: 8.4 },
        { ep: 10, title: "The Return Part 10", rating: 8.3 },
        { ep: 11, title: "The Return Part 11", rating: 8.9 },
        { ep: 12, title: "The Return Part 12", rating: 8.1 },
        { ep: 13, title: "The Return Part 13", rating: 9.0 },
        { ep: 14, title: "The Return Part 14", rating: 9.2 },
        { ep: 15, title: "The Return Part 15", rating: 8.8 },
        { ep: 16, title: "The Return Part 16", rating: 9.3 },
        { ep: 17, title: "The Return Part 17", rating: 9.5 },
        { ep: 18, title: "The Return Part 18", rating: 9.6 },
      ],
    },
  ],
};

export const MOCK_CALENDAR = [
  { date: "Today", entries: [
    { title: "Severance", type: "New Episode", episode: "S02E08", service: "Apple TV+", poster: "https://image.tmdb.org/t/p/w300/bxAg0poFKAoRqKJPm4dv7OvNajl.jpg" },
  ]},
  { date: "Tomorrow", entries: [
    { title: "The Bear", type: "Season Premiere", episode: "S04E01", service: "Hulu", poster: "https://image.tmdb.org/t/p/w300/sHm9SBSJMFaHiGXfMSAHM3CLUXB.jpg" },
  ]},
  { date: "Apr 18", entries: [
    { title: "28 Years Later", type: "Film Release", service: "In Theaters", poster: "https://image.tmdb.org/t/p/w300/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg" },
    { title: "Andor", type: "Season Premiere", episode: "S02E01", service: "Disney+", poster: "https://image.tmdb.org/t/p/w300/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg" },
  ]},
];
